name: Automation Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  automation-tests:
    name: Automation Tests (API + UI + GraphQL)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin
          cache: maven

      - name: Run all tests
        run: mvn clean test

      - name: Verify Allure results
        run: |
          echo "ALLURE RESULTS CHECK:"
          ls -R target/allure-results || true
          echo "TOTAL FILES:"
          find target/allure-results -type f | wc -l

      - name: Install Allure CLI
        run: |
          curl -o allure.tgz -Ls https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -zxvf allure.tgz
          sudo mv allure-2.27.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Generate Allure Report
        run: |
          allure generate target/allure-results -o allure-report --clean

      - name: Publish Allure report
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report
          force_orphan: true

      - name: Add Allure Report link to summary
        if: always()
        run: |
          echo "### QA Automation Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "[Open Allure Report](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/)" >> $GITHUB_STEP_SUMMARY